### ISSUE TITLE
Destroy method missing

### ISSUE THREAD

**Issue by leolux** [tborychowski/perfecttooltip#11]
In order to free resources every plugin should expose some method to destroy/stop the plugin as explained in http://acuriousanimal.com/blog/2013/02/25/things-i-learned-creating-a-jquery-plugin-part-ii/
```
    destroy: function() {
        ...
	},
```

**Comment by tborychowski** [comment]
did you read the code?
Isn't that sufficient?
https://github.com/tborychowski/perfecttooltip/blob/master/js/jquery.tooltip.js#L315

**Comment by leolux** [comment]
Sorry for my mistake! I read the wrong source code accidentally (code from a similar component). Sure, everything is fine.
