### ISSUE TITLE
Do we have a way to update tooltip text dynamically

### ISSUE THREAD

**Issue by jithureddy** [tborychowski/perfecttooltip#13]
For example I have element for which the description changes always. If I only bind the value during initialisation then there is no way the tooltip is going to show the new description.
Is there  a way to add some callback or expose function which updates the text for the specified selector (for example id)

**Comment by jithureddy** [comment]
@tborychowski Any urgent help would be appreciated. Thanks

**Comment by tborychowski** [comment]
I don't need to have a way, as the tooltip is not there until you need it :-)
e.g. 
- you have an element with a `title` attribute
- you attach the tooltip
- if you want to change the text - just change the `title` value

(alternatively you can use `data-title` instead of the title)

**Comment by tborychowski** [comment]
also- the project is not maintained anymore (who's using jquery nowadays!) so if that doesn't work - please use one of the fine tooltip libs out there:
https://www.npmjs.com/browse/keyword/tooltips
