### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by fcaballero** [tborychowski/perfecttooltip#8]
Hi @tborychowski,

I would like to use your plugin, but the company where I'm working asks me that every plugin we'd want to use must have a license in order to avoid troubles.

May you please add a license in the readme, bower.json and package.json files?

Thanks!

**Comment by tborychowski** [comment]
Hi,

No problem, will do that today :-)

**Comment by tborychowski** [comment]
@fcaballero, I added the license. Let me know if that's fine, or if you need anything else :-)

**Comment by fcaballero** [comment]
Hi @tborychowski, I think it's fine, thanks a lot ;)
